#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

[ -f "$SCRIPT_DIR/../../os" ] && source "$SCRIPT_DIR/../../os"
[ -f "$SCRIPT_DIR/../../func" ] && source "$SCRIPT_DIR/../../func"
echo "the os is $OS"

if [ ! -e "$HOME/.config/nvim" ]; then
	echo "no nvim"
	exit 0
fi

INSTALL_PATH="$HOME/.config/nvim/"
[[ "$CUSTOM" == "true" ]] && SUBTREE="" || SUBTREE="/lua/custom/"
INSTALL_PATH+=$SUBTREE

mkdir -p "$INSTALL_PATH"

main() {
	opts "$@"

	cp "$SCRIPT_DIR/mcp.json" "$HOME"

	CLUADE="$HOME/Library/Application Support/Claude/claude_desktop_config.json"

	if [[ -L $CLUADE ]]; then
		rm -rf "$CLUADE"
		ln -s "$HOME/mcp.json" "$CLUADE"
	fi

	CURSOR="$HOME/.cursor/mcp.json"
	if [[ -L $CURSOR ]]; then
		rm -rf "$CURSOR"
		ln -s "$HOME/mcp.json" "$CURSOR"
	fi

	echo "nvchad/v3 install path from: $SCRIPT_DIR/$SUBTREE/* to: $INSTALL_PATH"
	if [ -z "$SUBTREE" ]; then
		cp -r "$SCRIPT_DIR"/* "$INSTALL_PATH"
	else
		cp -r "$SCRIPT_DIR/$SUBTREE/"* "$INSTALL_PATH"
	fi

	if [ $PACKAGE = true ]; then
		PKGM=$(getpkgm)
		echo "install package for nvim configuration"
		# node
		# install nodejs "$PKGM"

		# nvm download and install
		curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

		# Load nvm for immediate use in this script
		export NVM_DIR="$HOME/.nvm"
		[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

		# Node.js
		nvm install 22

		# install npm "$PKGM"
		install delve "$PKGM"
		# pnpm
		PNPM=$(which pnpm)

		if [ -z "$PNPM" ]; then
			echo "install pnpm"
			curl -fsSL https://get.pnpm.io/install.sh | sh -
			#npm --global add pnpm
		fi
		# plugin
		install libmagickwand-dev "$PKGM"
		pnpm add -g @mermaid-js/mermaid-cli
	fi
}

main "$@"
