#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

mkdir -p ~/gitconfig
cp "$SCRIPT_DIR/.gitconfig" ~/.gitconfig

cp "$SCRIPT_DIR/github.gitconfig" ~/gitconfig
cp "$SCRIPT_DIR/workspace.gitconfig" ~/gitconfig
