#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

[ -f "$SCRIPT_DIR/../os" ] && source "$SCRIPT_DIR/../os"

cp "$SCRIPT_DIR/alacritty.yml" ~/.config/alacritty/
if [ "$OS" == "MAC" ]; then
	cp "$SCRIPT_DIR/mac/fonts.yml" ~/.config/alacritty/
elif [ "$OS" == "UBUNTU" ]; then
	cp "$SCRIPT_DIR/ubuntu/fonts.yml" ~/.config/alacritty/
fi
