#!/usr/bin/env bash

set -e

source ./os
source ./func

echo "the os is $OS"

main() {
	opts "$@"
	if [ $PACKAGE = true ]; then
		PKGM=$(getpkgm)
		echo "pkgm $PKGM"
		install fzf "$PKGM"
		install wget "$PKGM"
		install grc "$PKGM"
		install yq "$PKGM"
		install jq "$PKGM"
		install gh "$PKGM"
		install ripgrep "$PKGM"
		install bat "$PKGM"

		if [ "$OS" == "MAC" ]; then
			install protobuf "$PKGM"
		else
			install protobuf-compiler "$PKGM"
		fi

	fi

	# zsh
	# cp -r ./alacritty ~/.config

	cp .zshrc ~/.zshrc

	cp .tmux.conf ~/.tmux.conf
	tmux source-file ~/.tmux.conf

	if [ ! -e ~/.tmux/plugins/tpm ]; then
		git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
		"$HOME/.tmux/plugins/tpm/tpm"
	fi

	cd ./alacritty && ./install && cd ..
	cd ./gitconfig && ./install && cd ..

	[ -f .env.workspace ] && cp .env.workspace ~/.env.workspace

	cd ./colour-mysql-console && ./install "$@" && cd ..

	[ -d ~/.config/kitty ] && cp -r ./kitty/tmux/* ~/.config/kitty/
	[ -f ./vim/install ] && cd ./vim && ./install "$@" && cd ..
	[ -f ./scripts/install ] && cd ./scripts/ && ./install "$@" && cd ..

	install python3-pip "$PKGM"
}

getpkgm() {
	case $OS in
	'MAC') echo 'brew' ;;
	'UBUNTU') echo 'apt' ;;
	*) 'unknown os' ;;
	esac
}

install() {
	case $2 in
	'apt')
		if ! dpkg -s "$1" >/dev/null 2>&1; then
			echo -e "install.. \e[1;32m $1 \e[0m"
			sudo apt-get install "$1"
		fi
		;;
	'brew')
		INSTALLED=$(brew list "$1")
		if [ -z "$INSTALLED" ]; then
			echo -e "install.. \e[1;32m $1 \e[0m"
			brew install "$1"
		fi
		;;
	'pnpm')
		INSTALLED=$(pnpm list -g "$1")
		if [ -z "$INSTALLED" ]; then
			echo -e "install.. \e[1;32m $1 \e[0m"
			pnpm i -g "$1"
		fi
		;;
	*)
		echo "unknown command: $2"
		;;
	esac
}

main "$@"
