#!/usr/bin/env bash

source ./func

main() {
  opts "$@"
  if [ $PACKAGE = true ]; then
    install fzf brew
    install wget brew
    install grc brew
    install yq brew
    install jq brew
  fi


	cp .zshrc ~/.zshrc
	# zsh
	cp -r kitty/* ~/.config/kitty/
  [ -f ./vim/install ] && cd ./vim && ./install "$@"
  cd ..
  [ -f ./scripts/install ] && cd ./scripts/ && ./install "$@"
}

install() {
	case $2 in
	'brew')
		INSTALLED=$(brew list | grep "$1")
		if [ -z "$INSTALLED" ]; then
			brew install "$1"
		fi
		;;
	'pnpm')
		INSTALLED=$(pnpm list | grep "$1")
		if [ -z "$INSTALLED" ]; then
			pnpm i -g "$2"
		fi
		;;
	*)
		echo "unknown command: $2"
		;;
	esac
}

main "$@"
